General data

In [1]:
import pandas as pd
import numpy as np
import random
import string
import time

In [2]:
countries = ['\'Russia\'', '\'Japan\'', '\'Brazilia\'', '\'Ukrain\'', '\'USA\'', '\'Spain\'', '\'France\'', '\'China\'']
cities = ['\'Moscow\'', '\'Tokyo\'', '\'Brazilia\'', '\'Kiev\'', '\'Washington\'', '\'Madrid\'', '\'Paris\'', '\'Beijing\'']
sports = ['\'swimming\'', '\'tennis\'', '\'judo\'', '\'sambo\'', '\'figure skating\'', '\'skying\'', '\'gymnastic\'']

In [3]:
def generate_name():
    length1 = random.randint(2, 10)
    letters = string.ascii_lowercase
    res1 = ''.join(random.choice(letters) for i in range(length1))
    length2 = random.randint(2, 10)
    res2 = ''.join(random.choice(letters) for i in range(length2))
    res = (res1 + ' ' + res2).title()
    return '\'' + res + '\''

In [4]:
generate_name()

"'Wuvmnkdqld Jkqia'"

In [5]:
def generate_date():
    y = random.randint(1960, 2005)
    m = random.randint(1, 13)
    d = random.randint(1, 28)
    return (str)(d) + '.' + (str)(m) + '.' + (str)(y)

In [6]:
generate_date()

'4.12.1979'

Countries array

In [7]:
amount_countries = random.randint(3, 9)
amount_countries

3

In [8]:
countries_data_name = random.sample(countries, amount_countries)
countries_data_name

["'Ukrain'", "'China'", "'Brazilia'"]

In [9]:
countries_data_id = np.random.randint(1000, 9999, amount_countries)
countries_data_id

array([4190, 7286, 8439])

In [10]:
countries_data_area = np.random.randint(500, 20000, amount_countries)
countries_data_area

array([18207, 10739,  3865])

In [11]:
countries_data_population = np.random.randint(100000, 2000000000, amount_countries)
countries_data_population

array([1945091582, 1961191007,  679327445])

In [12]:
countries_data = np.transpose(np.array([countries_data_name, countries_data_id, countries_data_area, countries_data_population]))

In [13]:
countries_df = pd.DataFrame(countries_data, columns = ['name', 'id', 'area', 'population'])
countries_df = countries_df.set_index('id')
countries_df

name   area  population
id                                 
4190    'Ukrain'  18207  1945091582
7286     'China'  10739  1961191007
8439  'Brazilia'   3865   679327445

olympics

In [14]:
amount_ol = random.randint(1, amount_countries)
amount_ol

2

In [15]:
ol_data_id = np.random.randint(1000, 9999, amount_ol)
ol_data_id

array([4449, 4315])

In [16]:
ol_data_country_indeces = random.sample(range(0, amount_countries), amount_ol)
ol_data_country = [countries_data_id[i] for i in ol_data_country_indeces]
ol_data_country

[8439, 7286]

In [17]:
ol_data_city = [cities[i] for i in ol_data_country_indeces]
ol_data_city

["'Brazilia'", "'Tokyo'"]

In [18]:
ol_data_year = np.random.randint(1950, 2022, amount_ol)
ol_data_year

array([2014, 1982])

In [19]:
olympics_data = np.transpose(np.array([ol_data_id, ol_data_country, ol_data_city, ol_data_year]))
olympics_df = pd.DataFrame(olympics_data, columns = ['id', 'country', 'city', 'year'])
olympics_df = olympics_df.set_index('id')
olympics_df

country        city  year
id                            
4449    8439  'Brazilia'  2014
4315    7286     'Tokyo'  1982

events

In [23]:
amount_events = random.randint(2, 8)
amount_events

7

In [24]:
events_data_id = np.random.randint(1000, 9999, amount_events)
events_data_id

array([4304, 5258, 1392, 5808, 7756, 5866, 3079])

In [25]:
events_data_name = random.sample(sports, amount_events)
events_data_name

["'judo'",
 "'figure skating'",
 "'tennis'",
 "'swimming'",
 "'gymnastic'",
 "'sambo'",
 "'skying'"]

In [26]:
events_data_type = np.random.randint(0, 2, amount_events)
events_data_type

array([1, 0, 1, 1, 0, 0, 1])

In [29]:
events_data_ol_id = [ol_data_id[np.random.randint(0, len(ol_data_id))] for i in range(0, amount_events)]
events_data_ol_id

[4315, 4315, 4449, 4315, 4315, 4449, 4315]

In [30]:
events_data = np.transpose(np.array([events_data_id, events_data_name, events_data_type, events_data_ol_id]))
events_df = pd.DataFrame(events_data, columns = ['id', 'name', 'type', 'olympic_id'])
events_df = events_df.set_index('id')
events_df

name type olympic_id
id                                    
4304            'judo'    1       4315
5258  'figure skating'    0       4315
1392          'tennis'    1       4449
5808        'swimming'    1       4315
7756       'gymnastic'    0       4315
5866           'sambo'    0       4449
3079          'skying'    1       4315

players

In [31]:
amount_players = random.randint(1000, 10000)
amount_players

9337

In [32]:
players_data_name = [generate_name() for i in range(0, amount_players)]
players_data_name

["'Wmxcdlve Eqyh'",
 "'Syigo Bwwfnkdvbe'",
 "'Zmjwdl Gfyou'",
 "'Htpzfqqpf Ewidoak'",
 "'Kasrafsdi Jugvrcm'",
 "'Nfg Etakx'",
 "'Ukb Qpxqcqv'",
 "'Hiqofplr Xhbb'",
 "'Iouhspsdb Murwecdcnw'",
 "'Ruewfn Vqlvdzs'",
 "'Zwb Wfihe'",
 "'Spz Mf'",
 "'Fuxrozbrpg Jmbwczff'",
 "'Redgbeycn Umijxbu'",
 "'Ffzs Qnhj'",
 "'Sww Lfb'",
 "'Qitkdt Xmjxwqtj'",
 "'Ctecyy Kunebly'",
 "'Rp Ttwcbx'",
 "'Qxrmy Ezrh'",
 "'Fwtnicy Pgjmp'",
 "'Apxz Cvq'",
 "'Ebdg Dkshqewawi'",
 "'Mbqjbhonp Abg'",
 "'Vqalwkvly Lzeqv'",
 "'Gu Rp'",
 "'Pkdcvgsetp Dqepgclj'",
 "'Zlybzmeru Gjb'",
 "'Yuzkvl Gxwxl'",
 "'Sxu Plrjcedtth'",
 "'Kddumghcr Hrpyuvb'",
 "'Akicfei Xbv'",
 "'Arcvb Fcm'",
 "'Qhxsc Ks'",
 "'Jqeewv Czj'",
 "'Msfut Hiyj'",
 "'Sup Zixhtfvpyo'",
 "'Df Klw'",
 "'Zbhpuzgeh Hn'",
 "'Yqapptm Nyhsr'",
 "'Mbjhf Zcbiu'",
 "'Wwjnrbqsqz Zbwggruac'",
 "'Knanpkq Kzr'",
 "'Khhexthohr Xdvojqsfz'",
 "'Cjn Dseoqq'",
 "'Dvbtcynh Iizdusrf'",
 "'Koplz Psymzhwgkb'",
 "'Lgcuoqa Zhstzup'",
 "'Faurkka Zpvntln'",
 "'Pifycuyfij Qgrlu'",
 "'Tu

In [33]:
players_country_name = [countries[np.random.randint(0, len(countries))] for i in range(0, amount_players)]
players_country_name

["'USA'",
 "'China'",
 "'Ukrain'",
 "'China'",
 "'Ukrain'",
 "'Brazilia'",
 "'Brazilia'",
 "'China'",
 "'France'",
 "'China'",
 "'USA'",
 "'France'",
 "'Russia'",
 "'Brazilia'",
 "'China'",
 "'Ukrain'",
 "'Russia'",
 "'Russia'",
 "'Japan'",
 "'Japan'",
 "'USA'",
 "'USA'",
 "'Japan'",
 "'Ukrain'",
 "'China'",
 "'France'",
 "'Japan'",
 "'Japan'",
 "'Brazilia'",
 "'China'",
 "'China'",
 "'France'",
 "'Brazilia'",
 "'Spain'",
 "'Spain'",
 "'China'",
 "'USA'",
 "'Ukrain'",
 "'China'",
 "'USA'",
 "'Brazilia'",
 "'Brazilia'",
 "'Ukrain'",
 "'France'",
 "'Japan'",
 "'China'",
 "'Japan'",
 "'Russia'",
 "'USA'",
 "'Russia'",
 "'China'",
 "'China'",
 "'Japan'",
 "'Japan'",
 "'Brazilia'",
 "'France'",
 "'Spain'",
 "'Russia'",
 "'France'",
 "'France'",
 "'France'",
 "'Brazilia'",
 "'Spain'",
 "'USA'",
 "'Spain'",
 "'China'",
 "'Ukrain'",
 "'France'",
 "'USA'",
 "'USA'",
 "'Russia'",
 "'Brazilia'",
 "'Russia'",
 "'USA'",
 "'Japan'",
 "'USA'",
 "'USA'",
 "'Russia'",
 "'Spain'",
 "'France'",
 "'Ukrain

In [34]:
players_data_birthdate = [generate_date() for i in range(0, amount_players)]
players_data_birthdate

['10.5.2003',
 '9.5.1997',
 '3.4.1967',
 '28.7.2003',
 '9.1.1992',
 '4.12.1998',
 '1.2.1992',
 '18.10.1993',
 '12.4.2004',
 '8.3.1983',
 '8.9.1968',
 '23.13.2002',
 '20.5.1967',
 '22.13.1986',
 '15.10.1981',
 '5.5.2001',
 '16.1.1974',
 '16.12.1974',
 '1.1.1998',
 '20.7.1991',
 '22.4.1966',
 '9.7.1984',
 '12.2.1975',
 '19.9.1960',
 '8.11.1963',
 '21.1.1978',
 '11.11.2003',
 '9.7.1975',
 '15.5.1987',
 '18.4.1988',
 '25.4.2001',
 '17.7.1969',
 '6.11.1972',
 '1.2.1961',
 '13.6.1984',
 '13.13.1980',
 '4.7.2004',
 '2.12.1967',
 '18.8.1989',
 '2.6.1997',
 '12.11.1968',
 '3.5.1976',
 '1.10.1996',
 '27.7.1963',
 '25.11.1992',
 '23.10.1963',
 '26.9.1973',
 '11.4.1985',
 '24.3.1983',
 '25.3.2004',
 '3.8.1985',
 '7.7.1977',
 '15.13.1980',
 '12.6.1970',
 '20.7.2003',
 '20.11.2003',
 '6.13.1989',
 '26.9.2001',
 '4.1.1981',
 '11.13.1968',
 '22.4.1978',
 '22.2.1980',
 '3.5.1994',
 '17.1.1966',
 '15.2.2001',
 '22.4.2004',
 '11.9.1981',
 '24.2.2000',
 '19.10.1983',
 '11.4.1990',
 '15.10.1973',
 '26.7.19

In [35]:
from random import shuffle

In [36]:
x = [i + 1000 for i in range(amount_players)]
shuffle(x)
players_data_id = x
players_data_id

[3740,
 4488,
 3071,
 7755,
 9038,
 1535,
 1022,
 1381,
 5309,
 6707,
 1129,
 5116,
 1373,
 3958,
 3896,
 1376,
 9945,
 2491,
 5717,
 3190,
 8539,
 6957,
 7549,
 5877,
 8376,
 1418,
 6418,
 8479,
 6139,
 2890,
 7150,
 5430,
 7098,
 6508,
 8537,
 9009,
 8706,
 5406,
 7700,
 9294,
 4275,
 8236,
 5808,
 6539,
 9667,
 9678,
 6737,
 8356,
 5282,
 3520,
 8912,
 5858,
 3008,
 9125,
 9674,
 4571,
 9159,
 1306,
 5227,
 2542,
 9409,
 9130,
 5911,
 5270,
 2138,
 6563,
 1922,
 8885,
 8895,
 7912,
 8693,
 10092,
 1623,
 2023,
 4594,
 9905,
 6107,
 10019,
 7717,
 1273,
 1739,
 8861,
 9642,
 6920,
 6162,
 6814,
 3843,
 3426,
 4828,
 7712,
 2485,
 9813,
 3446,
 5752,
 3556,
 1883,
 1645,
 8676,
 2519,
 9068,
 8743,
 3438,
 4734,
 7427,
 6173,
 3439,
 9095,
 3147,
 5507,
 3380,
 1600,
 3572,
 5171,
 6337,
 2478,
 7244,
 9792,
 7657,
 9733,
 9257,
 9228,
 3333,
 2224,
 5849,
 4862,
 4309,
 8157,
 3964,
 3353,
 10181,
 4416,
 10124,
 5278,
 2316,
 6792,
 3881,
 5465,
 6648,
 3440,
 1068,
 9574,
 10087,
 

In [37]:
players_data = np.transpose(np.array([players_data_name, players_country_name, players_data_birthdate, players_data_id]))
players_df = pd.DataFrame(players_data, columns = ['name', 'country', 'birthday', 'id'])
players_df = players_df.set_index('id')
players_df

name     country    birthday
id                                                    
3740           'Wmxcdlve Eqyh'       'USA'   10.5.2003
4488        'Syigo Bwwfnkdvbe'     'China'    9.5.1997
3071            'Zmjwdl Gfyou'    'Ukrain'    3.4.1967
7755       'Htpzfqqpf Ewidoak'     'China'   28.7.2003
9038       'Kasrafsdi Jugvrcm'    'Ukrain'    9.1.1992
1535               'Nfg Etakx'  'Brazilia'   4.12.1998
1022             'Ukb Qpxqcqv'  'Brazilia'    1.2.1992
1381           'Hiqofplr Xhbb'     'China'  18.10.1993
5309    'Iouhspsdb Murwecdcnw'    'France'   12.4.2004
6707          'Ruewfn Vqlvdzs'     'China'    8.3.1983
1129               'Zwb Wfihe'       'USA'    8.9.1968
5116                  'Spz Mf'    'France'  23.13.2002
1373     'Fuxrozbrpg Jmbwczff'    'Russia'   20.5.1967
3958       'Redgbeycn Umijxbu'  'Brazilia'  22.13.1986
3896               'Ffzs Qnhj'     'China'  15.10.1981
1376                 'Sww Lfb'    'Ukrain'    5.5.2001
9945         'Qitkdt Xmjxwqtj'    'Russia'   16.1.1974
2491          'Ctecyy Kunebly'    'Russia'  16.12.1974
5717               'Rp Ttwcbx'     'Japan'    1.1.1998
3190              'Qxrmy Ezrh'     'Japan'   20.7.1991
8539           'Fwtnicy Pgjmp'       'USA'   22.4.1966
6957                'Apxz Cvq'       'USA'    9.7.1984
7549         'Ebdg Dkshqewawi'     'Japan'   12.2.1975
5877           'Mbqjbhonp Abg'    'Ukrain'   19.9.1960
8376         'Vqalwkvly Lzeqv'     'China'   8.11.1963
1418                   'Gu Rp'    'France'   21.1.1978
6418     'Pkdcvgsetp Dqepgclj'     'Japan'  11.11.2003
8479           'Zlybzmeru Gjb'     'Japan'    9.7.1975
6139            'Yuzkvl Gxwxl'  'Brazilia'   15.5.1987
2890          'Sxu Plrjcedtth'     'China'   18.4.1988
...                        ...         ...         ...
5855               'Olu Mktbh'    'France'    8.1.1987
6125   'Xzbkkrqwib Varxzzuhxi'    'Russia'    2.1.1965
3097               'Kdgzpo Kf'    'Russia'   7.11.1970
2871          'Naxtavgtv Jjfp'  'Brazilia'   1.10.2002
4797        'Gsrff Dzdlxdfavv'     'Spain'   19.3.1996
6592                'Acd Wybd'       'USA'    9.9.1964
6089            'Fkf Pnfjozuk'     'Spain'   13.1.1986
8301        'Giudscaho Bgypei'     'Spain'    3.3.1979
8255          'Kgbvnls Byfwki'  'Brazilia'  27.10.1971
10326         'Kpbh Ngwutxzgn'     'Spain'   26.9.1981
8571                  'Cqj Ad'    'Russia'   22.8.1969
7434           'Ugfxzihfrc Wn'    'France'    6.9.1967
5476    'Jkuhpwqsk Scocgzjriq'     'Spain'   28.5.1990
5153                'Qdqw Uea'     'China'  27.13.1981
2636                 'Iwew Ar'    'Russia'   26.2.2001
9252                   'Hb Mo'  'Brazilia'   11.7.1994
7769            'Uh Mqqmfjufd'  'Brazilia'    5.6.1971
7004           'Bvjdlmu Lgehv'       'USA'   20.4.1981
7074             'Snwnhx Zakc'  'Brazilia'   5.12.1979
5234       'Efjwvkz Syczoqtsp'    'Ukrain'   18.5.2000
6340         'Crvus Pbmpndkcz'     'Japan'   16.1.2000
5253       'Kmhwtkwsm Eicmsjw'       'USA'    8.4.1971
1056         'Uacciatrtb Vqfs'  'Brazilia'    6.9.1970
4726              'Noe Clwghr'     'Japan'  12.12.1991
4219         'Uqnjgw Jubxumez'    'Russia'   25.4.1961
1921        'Xoxqhlx Dterkwhs'    'Russia'  22.13.1970
2246       'Owwguamdpd Dgzdlu'     'Japan'    2.3.1964
7807      'Qyxswxd Uvphaiapyh'  'Brazilia'   17.6.1999
2697           'Kcx Odtuwxkwr'  'Brazilia'    1.4.1982
7149          'Esmvod Bfvmrlv'     'Spain'   16.8.1994

[9337 rows x 3 columns]

results

In [38]:
amount_results = amount_events * 3
amount_results

21

In [39]:
results_data_pl_id = [players_data_id[np.random.randint(0, len(players_data_id))] for i in range(0, amount_results)]
results_data_pl_id

[5266,
 3782,
 6488,
 3899,
 9953,
 5887,
 3709,
 8381,
 5753,
 7343,
 3985,
 6259,
 7259,
 6590,
 2779,
 3034,
 9625,
 1405,
 10197,
 7957,
 1521]

In [40]:
results_data_ev_id = np.repeat(events_data_id, 3)
results_data_ev_id

array([4304, 4304, 4304, 5258, 5258, 5258, 1392, 1392, 1392, 5808, 5808,
       5808, 7756, 7756, 7756, 5866, 5866, 5866, 3079, 3079, 3079])

In [64]:
results_data_medal = ['\'GOLD\'' if i % 3 == 0 else '\'SILVER\'' if i % 3 == 1 else '\'BRONZE\'' for i in range(0,amount_results)]
results_data_medal

["'GOLD'",
 "'SILVER'",
 "'BRONZE'",
 "'GOLD'",
 "'SILVER'",
 "'BRONZE'",
 "'GOLD'",
 "'SILVER'",
 "'BRONZE'",
 "'GOLD'",
 "'SILVER'",
 "'BRONZE'",
 "'GOLD'",
 "'SILVER'",
 "'BRONZE'",
 "'GOLD'",
 "'SILVER'",
 "'BRONZE'",
 "'GOLD'",
 "'SILVER'",
 "'BRONZE'"]

In [65]:
results_data_id = np.random.randint(1000, 9999, amount_results)
results_data_id

array([5168, 8006, 5947, 2745, 3675, 2825, 2182, 9533, 9178, 1884, 3473,
       4007, 3150, 1683, 3870, 6506, 6640, 3876, 2878, 8689, 3442])

In [66]:
results_data = np.transpose(np.array([results_data_pl_id, results_data_ev_id,results_data_medal, results_data_id]))
results_df = pd.DataFrame(results_data, columns = ['player_id', 'event_id', 'medal', 'id'])
results_df = results_df.set_index('id')
results_df

player_id event_id     medal
id                               
5168      5266     4304    'GOLD'
8006      3782     4304  'SILVER'
5947      6488     4304  'BRONZE'
2745      3899     5258    'GOLD'
3675      9953     5258  'SILVER'
2825      5887     5258  'BRONZE'
2182      3709     1392    'GOLD'
9533      8381     1392  'SILVER'
9178      5753     1392  'BRONZE'
1884      7343     5808    'GOLD'
3473      3985     5808  'SILVER'
4007      6259     5808  'BRONZE'
3150      7259     7756    'GOLD'
1683      6590     7756  'SILVER'
3870      2779     7756  'BRONZE'
6506      3034     5866    'GOLD'
6640      9625     5866  'SILVER'
3876      1405     5866  'BRONZE'
2878     10197     3079    'GOLD'
8689      7957     3079  'SILVER'
3442      1521     3079  'BRONZE'

## Получили таблицы:

In [44]:
countries_df

name   area  population
id                                 
4190    'Ukrain'  18207  1945091582
7286     'China'  10739  1961191007
8439  'Brazilia'   3865   679327445

In [45]:
olympics_df

country        city  year
id                            
4449    8439  'Brazilia'  2014
4315    7286     'Tokyo'  1982

In [46]:
events_df

name type olympic_id
id                                    
4304            'judo'    1       4315
5258  'figure skating'    0       4315
1392          'tennis'    1       4449
5808        'swimming'    1       4315
7756       'gymnastic'    0       4315
5866           'sambo'    0       4449
3079          'skying'    1       4315

In [47]:
players_df.head()

name   country   birthday
id                                            
3740      'Wmxcdlve Eqyh'     'USA'  10.5.2003
4488   'Syigo Bwwfnkdvbe'   'China'   9.5.1997
3071       'Zmjwdl Gfyou'  'Ukrain'   3.4.1967
7755  'Htpzfqqpf Ewidoak'   'China'  28.7.2003
9038  'Kasrafsdi Jugvrcm'  'Ukrain'   9.1.1992

In [67]:
results_df.head()

player_id event_id     medal
id                               
5168      5266     4304    'GOLD'
8006      3782     4304  'SILVER'
5947      6488     4304  'BRONZE'
2745      3899     5258    'GOLD'
3675      9953     5258  'SILVER'

### Заполняем таблицу

In [58]:
def fill_table(df, name_table):
    res = []
    for i in range(df.shape[0]):
        s = 'insert into ' + name_table + ' values (' + ', '.join(df.iloc[i]) + ');'
        res.append(s)
    return res

In [69]:
fill_list = []

In [72]:
fill_list = fill_list + fill_table(countries_df, 'countries')
fill_list

["insert into countries values ('Ukrain', 18207, 1945091582);",
 "insert into countries values ('China', 10739, 1961191007);",
 "insert into countries values ('Brazilia', 3865, 679327445);"]

In [73]:
fill_list = fill_list + fill_table(olympics_df, 'olympics')
fill_list

["insert into countries values ('Ukrain', 18207, 1945091582);",
 "insert into countries values ('China', 10739, 1961191007);",
 "insert into countries values ('Brazilia', 3865, 679327445);",
 "insert into olympics values (8439, 'Brazilia', 2014);",
 "insert into olympics values (7286, 'Tokyo', 1982);"]

In [74]:
fill_list = fill_list + fill_table(events_df, 'events')
fill_list

["insert into countries values ('Ukrain', 18207, 1945091582);",
 "insert into countries values ('China', 10739, 1961191007);",
 "insert into countries values ('Brazilia', 3865, 679327445);",
 "insert into olympics values (8439, 'Brazilia', 2014);",
 "insert into olympics values (7286, 'Tokyo', 1982);",
 "insert into events values ('judo', 1, 4315);",
 "insert into events values ('figure skating', 0, 4315);",
 "insert into events values ('tennis', 1, 4449);",
 "insert into events values ('swimming', 1, 4315);",
 "insert into events values ('gymnastic', 0, 4315);",
 "insert into events values ('sambo', 0, 4449);",
 "insert into events values ('skying', 1, 4315);"]

In [75]:
fill_list = fill_list + fill_table(players_df, 'players')
fill_list 

["insert into countries values ('Ukrain', 18207, 1945091582);",
 "insert into countries values ('China', 10739, 1961191007);",
 "insert into countries values ('Brazilia', 3865, 679327445);",
 "insert into olympics values (8439, 'Brazilia', 2014);",
 "insert into olympics values (7286, 'Tokyo', 1982);",
 "insert into events values ('judo', 1, 4315);",
 "insert into events values ('figure skating', 0, 4315);",
 "insert into events values ('tennis', 1, 4449);",
 "insert into events values ('swimming', 1, 4315);",
 "insert into events values ('gymnastic', 0, 4315);",
 "insert into events values ('sambo', 0, 4449);",
 "insert into events values ('skying', 1, 4315);",
 "insert into players values ('Wmxcdlve Eqyh', 'USA', 10.5.2003);",
 "insert into players values ('Syigo Bwwfnkdvbe', 'China', 9.5.1997);",
 "insert into players values ('Zmjwdl Gfyou', 'Ukrain', 3.4.1967);",
 "insert into players values ('Htpzfqqpf Ewidoak', 'China', 28.7.2003);",
 "insert into players values ('Kasrafsdi Jugvr

In [76]:
fill_list = fill_list + fill_table(results_df, 'results')
fill_list

["insert into countries values ('Ukrain', 18207, 1945091582);",
 "insert into countries values ('China', 10739, 1961191007);",
 "insert into countries values ('Brazilia', 3865, 679327445);",
 "insert into olympics values (8439, 'Brazilia', 2014);",
 "insert into olympics values (7286, 'Tokyo', 1982);",
 "insert into events values ('judo', 1, 4315);",
 "insert into events values ('figure skating', 0, 4315);",
 "insert into events values ('tennis', 1, 4449);",
 "insert into events values ('swimming', 1, 4315);",
 "insert into events values ('gymnastic', 0, 4315);",
 "insert into events values ('sambo', 0, 4449);",
 "insert into events values ('skying', 1, 4315);",
 "insert into players values ('Wmxcdlve Eqyh', 'USA', 10.5.2003);",
 "insert into players values ('Syigo Bwwfnkdvbe', 'China', 9.5.1997);",
 "insert into players values ('Zmjwdl Gfyou', 'Ukrain', 3.4.1967);",
 "insert into players values ('Htpzfqqpf Ewidoak', 'China', 28.7.2003);",
 "insert into players values ('Kasrafsdi Jugvr

### Заполняем файл

In [77]:
f = open( 'insert.txt', 'w' )
f.write('\n'.join(fill_list));